[package]
name = "cw-orch-polytone"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch = { workspace = true, features=["daemon"] }

polytone-note = { workspace = true, features=["interface"] }
polytone-proxy = { workspace = true, features=["interface"] }
polytone-voice = { workspace = true, features=["interface"] }

[dev-dependencies]
anyhow.workspace = true
